const ROUTES = {
  PLACE_DETAIL: 'PLACE_DETAIL',
};

const PARAMS = {
  CHANGE_HOME_SCREEN_TYPE: 'CHANGE_HOME_SCREEN_TYPE',
  ON_TOGGLE_DARK_LAYER: 'ON_TOGGLE_DARK_LAYER',
  ON_TYPE_PLACE_NAME: 'ON_TYPE_PLACE_NAME',
  ON_SEARCH_PLACE: 'ON_SEARCH_PLACE',
  TOGGLE_FILTER: 'TOGGLE_FILTER',
};

export default {
  ROUTES,
  PARAMS,
};
